### ISSUE TITLE
Make the following adjustements from this section

### ISSUE THREAD

**Issue by sheldon-welinga** [Lesley-w19/Dominion#2]
https://github.com/Lesley-w19/Dominion/blob/a7882a288cf80623b5699769f2bc39a38cd8881c/landing%20page/style.css#L30

**Remove the body styling on line 30-32** 

**adjust this line 38 to the one below**
`/* --------------adjusted today------------- */
.header {
  display: flex;
  justify-content: space-around;
  position: relative;
}
/* --------------adjusted today---------- */`

**adjust line 84 - 94 to the one below**
`/* ----------- adjusted today-------------- */
.btn1 {
  transform: rotate(-45deg);
  transition: 0.3s ease-in-out;
  position: absolute;
  margin: 0;
}

.btn2 {
  transform: rotate(45deg);
  transition: 0.3s ease-in-out;
  position: absolute;
}
/*--------------adjusted today-------------*/`

**adjust line 138 - 154 to the one below**
`/*-------------adjusted today---------  */
.navlinks ul {
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
}
.navlinks ul li {
  margin: 0.5rem;
  padding: 0.2rem;
}
.navlinks ul li a {
  text-transform: uppercase;
  font-size: 1rem;
  font-family: Verdana, Geneva, Tahoma, sans-serif;
  color: white;
  letter-spacing: 0.1rem;
  border-bottom: 0.05rem solid white;
}
/* -------------end adjusted today------------ */`

**Adjust the @media query section to the one below**
`/* adjusted today */
@media (min-width: 768px) {
  header {
    position: fixed;
    height: 100vh;
    width: 30vw;
    padding: 0;
  }

  header .navlinks {
    position: absolute;
    width: 100%;
    bottom: 0;
    padding: 1rem;
  }

  header .navbar {
    display: block;
  }

  .main {
    min-height: 100vh;
    width: 70vw;
    margin-left: 30vw;
  }
}
/* end of adjusted today */`

**Comment by Lesley-w19** [comment]
Thank you for the adjustment. Confirming that I will make the needed
changes and then get back to you.
Have a nice afternoon.

**Comment by sheldon-welinga** [comment]
Ok sure, Nice afternoon to you too
